"""Interop test: decrypt an export file produced by the Dart app.

The fixture `fixture_export.json` is generated by `tool/export_fixture.dart`
(run `dart run tool/export_fixture.dart` from the project root). This proves the
Python bot reads exactly what the Flutter app writes (Argon2id + AES-256-GCM).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from vaultfile import decrypt_export  # noqa: E402

FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixture_export.json")


def test_decrypts_dart_fixture():
    payload = decrypt_export(FIXTURE, "fixture-pass")
    servers = payload["servers"]
    secrets = payload["secrets"]
    assert servers[0]["name"] == "Alpha"
    assert servers[0]["host"] == "203.0.113.10"
    assert secrets["s1"]["password"] == "hunter2"


def test_rejects_wrong_password():
    try:
        decrypt_export(FIXTURE, "wrong-password")
    except Exception:
        return
    raise AssertionError("wrong password should have failed")


if __name__ == "__main__":
    test_decrypts_dart_fixture()
    print("OK: decrypted Dart fixture")
    test_rejects_wrong_password()
    print("OK: wrong password rejected")
    print("ALL INTEROP TESTS PASSED")
