import 'package:flutter/material.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('ru'),
    Locale('en'),
  ];

  String t(String key) {
    final language = locale.languageCode;
    return _values[language]?[key] ?? _values['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'ru': {
      'addServer': 'Добавить сервер',
      'appSubtitle': 'Безопасное управление VPS',
      'backups': 'Бэкапы',
      'cancel': 'Отмена',
      'catalog': 'Каталог сервисов',
      'confirmInstall': 'Подтвердить установку',
      'confirmInstallStub': 'Реальная установка пока отключена',
      'cpu': 'CPU',
      'dark': 'Тёмная',
      'dangerousActions': 'Опасные действия',
      'disk': 'Диск',
      'dryRun': 'Dry-run',
      'dryRunHint': 'Предпросмотр ничего не выполняет на сервере.',
      'emptyServers': 'Серверов пока нет',
      'fingerprint': 'SSH fingerprint',
      'files': 'Файлы',
      'group': 'Группа',
      'host': 'IP или домен',
      'installedServices': 'Установленные сервисы',
      'installedServicesStub': 'Карточки установленных сервисов появятся после включения выполнения сценариев.',
      'language': 'Язык',
      'light': 'Светлая',
      'lock': 'Заблокировать',
      'login': 'Логин',
      'logs': 'Логи',
      'logsStub': 'Live-логи установки будут передаваться сюда через SSH-ядро.',
      'masterPassword': 'Мастер-пароль',
      'name': 'Название',
      'noEventsYet': 'Событий пока нет.',
      'noSecretsStored': 'Пароль или ключ не сохраняются открытым текстом.',
      'note': 'Заметка',
      'openCatalog': 'Установить сервис',
      'openTerminal': 'Открыть терминал',
      'os': 'ОС',
      'passport': 'Паспорт сервера',
      'plugins': 'Плагины',
      'pluginsStub': 'Плагины проходят dry-run, подтверждение и откат, как встроенные сценарии.',
      'port': 'SSH-порт',
      'ports': 'Порты',
      'ram': 'RAM',
      'required': 'Обязательное поле',
      'riskPhrase': 'Для опасных действий нужна фраза: я понимаю риск',
      'save': 'Сохранить',
      'securityLog': 'Журнал безопасности',
      'secretReference': 'Ссылка на секрет',
      'serverCard': 'Карточка сервера',
      'servers': 'Серверы',
      'servicePlan': 'План установки',
      'settings': 'Настройки',
      'sshMetricsStub': 'Откройте «Паспорт сервера», чтобы собрать живые метрики по SSH.',
      'statusOffline': 'Не проверен',
      'system': 'Системная',
      'theme': 'Тема',
      'unlock': 'Открыть',
      'unknown': 'Неизвестно',
      'warning': 'Предупреждение',
      'authType': 'Тип доступа',
      'backupsEmpty': 'Бэкапов пока нет.',
      'close': 'Закрыть',
      'confirmAndRun': 'Подтвердить и установить',
      'createMasterPassword': 'Создать мастер-пароль',
      'execution': 'Установка',
      'installPath': 'Путь установки',
      'installedEmpty': 'Установленных сервисов пока нет.',
      'liveLog': 'Живой лог',
      'logsEmpty': 'Записей пока нет.',
      'noCredentialWarning':
          'Для этого сервера не сохранён пароль или ключ. Добавьте их в форме сервера.',
      'passphrase': 'Passphrase ключа (необязательно)',
      'password': 'Пароль',
      'privateKey': 'Приватный SSH-ключ (PEM)',
      'riskPhraseInput': 'Введите фразу подтверждения',
      'rollback': 'Откатить изменения',
      'rollbackDone': 'Откат завершён',
      'runInstall': 'Установить',
      'servicePort': 'Порт',
      'setupHint':
          'Первый запуск. Задайте мастер-пароль — им шифруются все секреты.',
      'status': 'Статус',
      'wrongPassword': 'Неверный мастер-пароль',
      'autoLock': 'Автоблокировка',
      'autoLockOff': 'Выключена',
      'minutesUnit': 'мин',
      'exportImport': 'Экспорт / импорт серверов',
      'exportImportHint':
          'Зашифрованный файл с серверами и секретами. Открывается отдельным паролем.',
      'filePath': 'Путь к файлу',
      'exportPassword': 'Пароль для экспорта',
      'importPassword': 'Пароль файла',
      'exportBtn': 'Экспортировать',
      'importBtn': 'Импортировать',
      'exportDone': 'Экспорт сохранён',
      'importDone': 'Импортировано серверов',
      'importFailed': 'Не удалось',
      'wrongFilePassword': 'Неверный пароль файла',
      'systemInfo': 'Система',
      'network': 'Сеть',
      'cores': 'Ядра',
      'loadAverage': 'Средняя загрузка',
      'kernel': 'Ядро ОС',
      'none': 'Нет',
      'refresh': 'Обновить',
      'collecting': 'Сбор данных…',
      'collectFailed': 'Не удалось собрать данные',
      'collected': 'Собрано',
      'recentErrors': 'Последние ошибки',
      'run': 'Выполнить',
      'commandHint': 'Введите команду…',
      'clearLog': 'Очистить',
      'history': 'История',
      'connectFailed': 'Не удалось подключиться',
      'reconnect': 'Переподключиться',
      'dangerousCommandTitle': 'Опасная команда',
      'edit': 'Редактировать',
      'delete': 'Удалить',
      'editServer': 'Редактировать сервер',
      'deleteServerConfirm': 'Удалить сервер и его сохранённый доступ?',
      'showCredential': 'Показать доступ',
      'credential': 'Доступ',
      'copy': 'Скопировать',
      'copied': 'Скопировано',
      'keepSecretHint': 'Оставьте пустым, чтобы не менять',
      'pluginFolder': 'Папка плагина',
      'loadPlugin': 'Загрузить плагин',
      'pluginLoaded': 'Плагин загружен',
      'pluginLoadFailed': 'Не удалось загрузить плагин',
      'noPlugins': 'Плагины не загружены',
      'online': 'В сети',
      'offline': 'Не в сети',
      'checking': 'Проверка…',
      'checkConnection': 'Проверить подключение',
      'checkAll': 'Проверить все',
      'serverGroups': 'Группы серверов',
      'addGroup': 'Добавить',
      'groupName': 'Название группы',
      'rename': 'Переименовать',
      'builtIn': 'Встроенная',
      'deleteGroupConfirm': 'Удалить группу? Её серверы перейдут в «Личные».',
      'deleteServiceConfirm':
          'Удалить карточку сервиса? Сервис на сервере не трогается.',
      'sftp': 'Файлы (SFTP)',
      'upload': 'Загрузить на сервер',
      'download': 'Скачать',
      'localPath': 'Локальный путь',
      'remotePath': 'Путь на сервере',
      'uploaded': 'Файл загружен',
      'downloaded': 'Файл скачан',
      'customMinutes': 'Свой…',
    },
    'en': {
      'addServer': 'Add server',
      'appSubtitle': 'Safe VPS management',
      'backups': 'Backups',
      'cancel': 'Cancel',
      'catalog': 'Service catalog',
      'confirmInstall': 'Confirm installation',
      'confirmInstallStub': 'Real installation is disabled for now',
      'cpu': 'CPU',
      'dark': 'Dark',
      'dangerousActions': 'Dangerous actions',
      'disk': 'Disk',
      'dryRun': 'Dry-run',
      'dryRunHint': 'Preview mode does not execute anything on the server.',
      'emptyServers': 'No servers yet',
      'fingerprint': 'SSH fingerprint',
      'files': 'Files',
      'group': 'Group',
      'host': 'IP or domain',
      'installedServices': 'Installed services',
      'installedServicesStub': 'Installed service cards will appear after scenario execution is enabled.',
      'language': 'Language',
      'light': 'Light',
      'lock': 'Lock',
      'login': 'Login',
      'logs': 'Logs',
      'logsStub': 'Live installation logs will be streamed here by the SSH core.',
      'masterPassword': 'Master password',
      'name': 'Name',
      'noEventsYet': 'No events yet.',
      'noSecretsStored': 'Password or key is not stored as plain text.',
      'note': 'Note',
      'openCatalog': 'Install service',
      'openTerminal': 'Open terminal',
      'os': 'OS',
      'passport': 'Server passport',
      'plugins': 'Plugins',
      'pluginsStub': 'Plugins go through dry-run, confirmation, and rollback like built-in scenarios.',
      'port': 'SSH port',
      'ports': 'Ports',
      'ram': 'RAM',
      'required': 'Required field',
      'riskPhrase': 'Dangerous actions require this phrase: I understand the risk',
      'save': 'Save',
      'securityLog': 'Security log',
      'secretReference': 'Secret reference',
      'serverCard': 'Server card',
      'servers': 'Servers',
      'servicePlan': 'Installation plan',
      'settings': 'Settings',
      'sshMetricsStub': 'Open Server passport to collect live metrics over SSH.',
      'statusOffline': 'Not checked',
      'system': 'System',
      'theme': 'Theme',
      'unlock': 'Unlock',
      'unknown': 'Unknown',
      'warning': 'Warning',
      'authType': 'Auth type',
      'backupsEmpty': 'No backups yet.',
      'close': 'Close',
      'confirmAndRun': 'Confirm & install',
      'createMasterPassword': 'Create master password',
      'execution': 'Installation',
      'installPath': 'Install path',
      'installedEmpty': 'No installed services yet.',
      'liveLog': 'Live log',
      'logsEmpty': 'No entries yet.',
      'noCredentialWarning':
          'No password or key is stored for this server. Add one in the server form.',
      'passphrase': 'Key passphrase (optional)',
      'password': 'Password',
      'privateKey': 'Private SSH key (PEM)',
      'riskPhraseInput': 'Type the confirmation phrase',
      'rollback': 'Roll back changes',
      'rollbackDone': 'Rollback finished',
      'runInstall': 'Install',
      'servicePort': 'Port',
      'setupHint':
          'First launch. Set a master password — it encrypts every secret.',
      'status': 'Status',
      'wrongPassword': 'Wrong master password',
      'autoLock': 'Auto-lock',
      'autoLockOff': 'Off',
      'minutesUnit': 'min',
      'exportImport': 'Export / import servers',
      'exportImportHint':
          'Encrypted file with servers and secrets. Opened with a separate password.',
      'filePath': 'File path',
      'exportPassword': 'Export password',
      'importPassword': 'File password',
      'exportBtn': 'Export',
      'importBtn': 'Import',
      'exportDone': 'Export saved',
      'importDone': 'Servers imported',
      'importFailed': 'Failed',
      'wrongFilePassword': 'Wrong file password',
      'systemInfo': 'System',
      'network': 'Network',
      'cores': 'Cores',
      'loadAverage': 'Load average',
      'kernel': 'Kernel',
      'none': 'None',
      'refresh': 'Refresh',
      'collecting': 'Collecting…',
      'collectFailed': 'Collection failed',
      'collected': 'Collected',
      'recentErrors': 'Recent errors',
      'run': 'Run',
      'commandHint': 'Type a command…',
      'clearLog': 'Clear',
      'history': 'History',
      'connectFailed': 'Connection failed',
      'reconnect': 'Reconnect',
      'dangerousCommandTitle': 'Dangerous command',
      'edit': 'Edit',
      'delete': 'Delete',
      'editServer': 'Edit server',
      'deleteServerConfirm': 'Delete this server and its stored credential?',
      'showCredential': 'Show credential',
      'credential': 'Credential',
      'copy': 'Copy',
      'copied': 'Copied',
      'keepSecretHint': 'Leave blank to keep current',
      'pluginFolder': 'Plugin folder',
      'loadPlugin': 'Load plugin',
      'pluginLoaded': 'Plugin loaded',
      'pluginLoadFailed': 'Failed to load plugin',
      'noPlugins': 'No plugins loaded',
      'online': 'Online',
      'offline': 'Offline',
      'checking': 'Checking…',
      'checkConnection': 'Check connection',
      'checkAll': 'Check all',
      'serverGroups': 'Server groups',
      'addGroup': 'Add',
      'groupName': 'Group name',
      'rename': 'Rename',
      'builtIn': 'Built-in',
      'deleteGroupConfirm': 'Delete group? Its servers move to "Personal".',
      'deleteServiceConfirm':
          'Remove the service card? The remote service is left untouched.',
      'sftp': 'Files (SFTP)',
      'upload': 'Upload',
      'download': 'Download',
      'localPath': 'Local path',
      'remotePath': 'Remote path',
      'uploaded': 'File uploaded',
      'downloaded': 'File downloaded',
      'customMinutes': 'Custom…',
    },
  };
}
